#!/usr/bin/env python3
"""
SonicStream PWA Build & Deployment Configuration Injector

Reads local configuration from `pwa_config.json` (or `pwa_config.example.json` if unconfigured)
and generates `web-pwa/config.js` so that sensitive URLs and SAS tokens are dynamically
injected into the Web PWA build without being checked into Git.
"""

import os
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOCAL_CONFIG_FILE = os.path.join(BASE_DIR, "pwa_config.json")
EXAMPLE_CONFIG_FILE = os.path.join(BASE_DIR, "pwa_config.example.json")
TARGET_JS_CONFIG = os.path.join(BASE_DIR, "web-pwa", "config.js")

def load_config():
    config_path = LOCAL_CONFIG_FILE if os.path.exists(LOCAL_CONFIG_FILE) else EXAMPLE_CONFIG_FILE
    print(f"[Build PWA] Loading configuration from: {os.path.basename(config_path)}")
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[Build PWA Warning] Failed to read {config_path}: {e}")
        return {}

def build_pwa():
    cfg = load_config()
    
    config_dict = {
        "azure_storage_account": cfg.get("azure_storage_account", ""),
        "azure_container": cfg.get("azure_container", "media"),
        "azure_sas_token": cfg.get("azure_sas_token", ""),
        "azure_client_id": cfg.get("azure_client_id", "51f81489-12ee-4a9e-aaae-a2591f45987d"),
        "onedrive_share_link": cfg.get("onedrive_share_link", "")
    }

    js_content = f"""// Auto-generated configuration for SonicStream Web PWA
// DO NOT EDIT DIRECTLY. Generated by build_pwa.py from pwa_config.json.
window.SONICSTREAM_CONFIG = {json.dumps(config_dict, indent=2)};
"""

    os.makedirs(os.path.dirname(TARGET_JS_CONFIG), exist_ok=True)
    with open(TARGET_JS_CONFIG, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"[Build PWA] Successfully generated '{os.path.relpath(TARGET_JS_CONFIG, BASE_DIR)}'")

if __name__ == "__main__":
    build_pwa()
